site: Konrad Rydzak personal website
url: https://konradrydzak.github.io/
title: Konrad Rydzak personal website
description: My personal website with blog posts, completed projects/courses/tutorials with comments, and more.
author:
  name: konradrydzak
  email: konradrydzakcontact@gmail.com
  url: https://konradrydzak.github.io/
permalink: pretty

baseurl: ""

highlighter: none

exclude:
  - .jekyll-cache

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"